# Ejercicio 1: 1, 2, y p ¡qué norma más chévere! (80 000 créditos)
Dado el vector x = [1, 2, . . . , 1000],
- a) (10 000 créditos) Calcule la norma 1 de x.
### Respuesta
    $$||x||_{1} = \sum^{1000}_{i=1}|a_{i}|$$
- b) (10 000 créditos) Calcule la norma 2 de x.
### Respuesta
    $$ ||x||_{1} = \sqrt{ \sum^{1000}_{i=1}a_{i}^{2}}$$
- c) (10 000 créditos) Calcule la norma p de x cuando p = 14.
    $$ ||x||_{1} = \sqrt[p]{ \sum^{1000}_{i=1}|a_{i}|^{p}}$$
- d) (50 000 créditos) Compruebe “experimentalmente” que: $\lim_{p\to\infty} ||x||_{p} = ||x||_{\infty}$, determine para qué valores de p, la norma p del vector x “se parece” a la norma infinito.

# Ejercicio 2: SELs, residuos y errores (150 000 créditos)
Dados el sistema de ecuaciones lineales:
$\begin{bmatrix}
1 & 1 \\
1.0000001 & 1
\end{bmatrix}\begin{bmatrix}
x1\\
x2
\end{bmatrix}=\begin{bmatrix}
2\\
2,0000001 
\end{bmatrix}$

que tiene solución exacta: $x = [1; 1]^t$, y la solución aproximada $\bar{x} = [−1; 3,0001]$:
- a) (20 000 créditos) Calcule el residual asociado a x.

In [6]:
import numpy as np
A = np.array([[1,1],[1.0000001,1]])
x = np.array([1,1])
x_ = np.array([-1,3.0001])
b = A@x
r = b - A@x_
print(r)

[-1.00e-04 -9.98e-05]


- b) (20 000 créditos) Calcule el error absoluto asociado a x

In [19]:
e = abs(x - x_)
e

array([2.    , 2.0001])

- c) (20 000 créditos) Calcule una solución del sistema usando la factorización PLU que está
    implementada en Python. Sea $x_P$ esa solución.

In [46]:
import scipy.linalg
s = np.array([2,2.0000001])
lu,piv = scipy.linalg.lu_factor(A)
xp = scipy.linalg.lu_solve((lu,piv),s)
xp

array([1., 1.])

- d) (20 000 créditos) Calcule el residual asociado a xp.

In [47]:
x = np.array([1,1])
b = A@x
r = b - A@xp
print(r)

[0.0000000e+00 4.4408921e-16]


- e) (20 000 créditos) Calcule el error absoluto asociado a xp.

In [54]:
e = abs(x-xp)
e

array([2.22044627e-09, 2.22044627e-09])

- f) (50 000 créditos) ¿Cuántas cifras significativas correctas tiene xp como aproximación de x?

# Ejercicio 3: Todo depende de la norma con que se mire (80000 créditos)
Dada la matriz
$
A =
\begin{pmatrix}
4 & -3 & 6 & 8 \\
1 & -2 & 7 & 9 \\
5 & 8 & 9 & -4 \\
3 & 2 & 7 & 1
\end{pmatrix}
$

calcule
- a) $||A||_1$ (10 000 créditos).
### Respuesta
    $$ ||A||_1 = \max_j \sum_{i=1}^{n} |a_{ij}|$$


In [33]:

A = np.array([[4,-3,6,8],[1,-2,7,9],[5,8,9,-4],[3,2,7,1]])
sol = 0
for i in A:
    temp = 0
    for j in i:
        temp += abs(j)
    sol = max(sol,temp)
print(sol)

26


- b) $||A||_2$ (10 000 créditos).
### Respuesta
    $$ ||A||_2 = \sqrt{\lambda_{max}(A^tA)}$$
    

In [56]:
eigenvalues = np.linalg.eig(A.transpose()@A)
max(eigenvalues[0])

310.5524598140576

- c) $||A||_∞$ (10 000 créditos).
$$||A||_∞ = \max_i \sum_{j=1}{n}|a_{ij}|$$

In [60]:
import numpy as np
A = np.array([[4,-3,6,8],[1,-2,7,9],[5,8,9,-4],[3,2,7,1]])
sol = 0
# recorrer las filas de la matriz transpuesta es equivalente a recorrer las columnas
for i in A.transpose():
    temp = 0
    for j in i:
        temp += abs(j)
    sol = max(sol,temp)
print(sol)

29


- d) $||A||_F$ (50 000 créditos).

Norma de Frobenius
$$ ||A||_F = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n} |a_{ij}|^2} = \sqrt{Traza(A^t*A)}$$

In [64]:
print(np.sqrt((A.transpose()@A).trace()))

22.561028345356956
