# DIA 1

# Tarea 1: Gotta identify them all
- Matriz Diagonal
- Matriz Triangular Superior
- Matriz Triangular Inferior
- matriz Ortogonal

# Tarea 2: Donde resuelve una eficiente, resuelven 2, 3, ¡y hasta k (con k menor que n)!


# Tarea 3: Método de Gauss + Profes de EDA = Implementación eficiente
Para evitar el intercambio físico de las filas de la matriz, se puede detinar un array de tamaño n, que va a contener los índies de las filas
de la matriz, en un inicio cada indice se encontraría en su posición inicial, y a medida que vaya siendo necesario hacer el cambio de filas,
solamente es necesario cambiar los índices de las filas señaladas. Para acceder a la fila deseada de la matriz, basta con indexar en el valor
que se encuentre en la posicion de la fila deseada en el array de índices

# Tarea 4: ¡3, 1, y 2! Qué permutación más chévere. . .
- a) Al realizar las permutaciones en la matriz ideintidad, y multiplicar ésta por otra matriz (A), se van a efectuar las mismas permutaciones en la matriz A, esto es, si se permutan las columnas 1 y 2 de la matriz ideintidad, el mismo cambio ocurrirá en la matriz resultante, o sea, el elemento en la posición i de la fila j en la matriz A se encontrará en la posición i' (donde i' es la pos en la q se encuentra el 1 en la fila i de P) de la matriz resultante de la multiplicación de P por A
- b) En cada una de las posiciones de la fila, cada elemento [i,j] de la matriz a va a ser multiplicado por el elemento [j,i] de la matriz P, 
     recorriendo la j desde 0-n para cada i, pero de cada una de estas multiplicaciones en cada fila va a haber solo un elemento en el que 
     no se anula, en este caso, para cada ieste va a ser la posición j en la que se encuentra el 1, por tanto, se va a realizar 
     la permutación al multiplicarse A por P
- c) Mediante una permutación de n, en el q el valor de cada posición es la columna que se ha permutado y se encuentra ahora allí
- d) En este caso en vez de permutar las columnas de A, se permutan las filas de A
- e) En este caso, se permutan las columnas
- f) En la matriz ideintidad, permutar las filas o las columanas tiene el mismo efecto, permutar la fila i, con la fila j es equivalente a permutar la columna i con la columna j
- g) Matriz de permutación

# DIA 2

 # Ejercicio 1: A = L*U (3x3)
 - a) Encuentre una matriz L1 tal que:
$$
    L_{1} * A = U_{21} = 
    \begin{bmatrix} 
         a_{11} & a_{12} & a_{13} \\
         0 & \overline{a_{22}} & \overline{a_{23}} \\
         a_{31} & a_{32} & a_{33}
    \end{bmatrix}  
$$
donde $U_{21} es la matriz que se obtendría después del primer paso del método
de Gauss.

### Respuesta
$$ 
l_1 =\frac{a_{21}}{a_{11}}\\ 
L_1 = 
\begin{bmatrix} 
    1 & 0 & 0 \\
    -\frac{a_{21}}{a_{11}} & 1 & 0 \\
    0 & 0 & 1
\end{bmatrix}
$$

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
L = np.array([[1,0,0],[-4,1,0],[0,0,1]])
L@A

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 7,  8,  9]])

- b) Encuentre una matriz L2 tal que:
$$
    L_{2} * A = U_{31} = 
    \begin{bmatrix} 
         a_{11} & a_{12} & a_{13} \\
         a_{21} & a_{22} & a_{23} \\
         0 & \overline{a_{32}}& \overline{a_{33}}
    \end{bmatrix}  
$$
donde $U_{31}$ es la matriz que se obtendría al aplicar un paso del método de
Gauss para, usando el elemento $a_{11}$ como pivote, obtener 0 en la posición
(3,1).

### Respuesta
$$ 
l_2 = \frac{a_{31}}{a_{11}}\\
L_2 = 
\begin{bmatrix} 
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    -\frac{a_{31}}{a_{11}} & 0 & 1
\end{bmatrix}
$$

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
L = np.array([[1,0,0],[0,1,0],[-7,0,1]])
L@A

array([[  1,   2,   3],
       [  4,   5,   6],
       [  0,  -6, -12]])

c) A partir de realizar operaciones matriciales con L1 y L2, obtenga una matriz
C1, tal que:

$$
    C_{1} * A = U_{1} = 
    \begin{bmatrix} 
         a_{11} & a_{12} & a_{13} \\
         0 & \overline{a_{22}} & \overline{a_{23}} \\
         0 & \overline{a_{32}}& \overline{a_{33}}
    \end{bmatrix}  
$$

donde $U_1$ es la matriz que se obtendría después de los dos primeros pasos del
método de Gauss.

### Respuesta
$$ 
C_1 = 
\begin{bmatrix} 
    1 & 0 & 0 \\
    -\frac{a_{21}}{a_{11}} & 1 & 0 \\
    -\frac{a_{31}}{a_{11}} & 0 & 1
\end{bmatrix}
$$

In [3]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
L = np.array([[1,0,0],[-4,1,0],[-7,0,1]])
L@A

array([[  1,   2,   3],
       [  0,  -3,  -6],
       [  0,  -6, -12]])

- d) Encuentre una matriz $L_3$ tal que:
$$
    L_{3} * A = U_{32} = 
    \begin{bmatrix} 
         a_{11} & a_{12} & a_{13} \\
         0 & \overline{a_{22}} & \overline{a_{23}} \\
         0 & 0 & \overline{\overline{a_{33}}}
    \end{bmatrix}  
$$
En este caso, la matriz $U_{32}$ debe ser la misma matriz que se obtendría después
de aplicar los tres pasos del método de Gauss.
Fíjate en el detalle que al multiplicar $L_3 ∗U_1$ no se puede modificar el cero en
la posición (3,1) ni los elementos en las dos primeras filas

### Respuesta 


$$ 
l_3 = \frac{\overline{a_{32}}}{\overline{a_{22}}}
\\
L_3 = 
\begin{bmatrix} 
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & -\frac{\overline{a_{32}}}{\overline{a_{22}}} & 1
\end{bmatrix}
$$


In [6]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
L = np.array([[1,0,0],[-4,1,0],[-7,0,1]])
L2 = np.array([[1,0,0],[0,1,0],[0,-2,1]])
A_2 = L@A
L2@A_2 

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 0,  0,  0]])

- e) A partir de realizar operaciones matriciales con $L_1$, $L_2$ y $L_3$, obtenga una
    matriz $C_{12}$, tal que:
    $$
    C_{12} * A = U_{32} = 
    \begin{bmatrix} 
         a_{11} & a_{12} & a_{13} \\
         0 & \overline{a_{22}} & \overline{a_{23}} \\
         0 & 0 & \overline{\overline{a_{33}}}
    \end{bmatrix}  
    $$
### Respuesta
$$
C_{12} * A = L_3*(L_1*L_2)*A =
    \begin{bmatrix} 
         a_{11} & a_{12} & a_{13} \\
         0 & \overline{a_{22}} & \overline{a_{23}} \\
         0 & 0 & \overline{\overline{a_{33}}}
    \end{bmatrix}  
    $$
    $$C_{12} = L_3*(L_1*L_2) $$

In [8]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
L = np.array([[1,0,0],[-4,1,0],[0,0,1]])
L2 = np.array([[1,0,0],[0,1,0],[-7,0,1]])
L3 = np.array([[1,0,0],[0,1,0],[0,-2,1]])
L3@(L@L2)@A

array([[ 1,  2,  3],
       [ 0, -3, -6],
       [ 0,  0,  0]])

- f) Demuestre que la matriz $C_{12}$ tiene determinante 1, y por lo tanto es inversible.
Esa demostración es muy sencilla: solo tienes que darte cuenta que las matrices $L_1$, $L_2$ y $L_3$ tienen todas determinante 1.
### Respuesta
Las Matrices:
$$
L_1 = \left|
\begin{bmatrix} 
    1 & 0 & 0 \\
    -\frac{a_{21}}{a_{11}} & 1 & 0 \\
    0 & 0 & 1
\end{bmatrix}\right| = 1 - 0 = 1\\
L_2 = \left|
\begin{bmatrix} 
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    -\frac{a_{31}}{a_{11}} & 0 & 1
\end{bmatrix}\right| = 1-0 = 1\\
L_3 = 
\left|
\begin{bmatrix} 
    1 & 0 & 0 \\
    0 & 1 & 0 \\
    0 & -\frac{\overline{a_{32}}}{\overline{a_{22}}} & 1
\end{bmatrix}\right| = 1-0 = 1
$$

todas tienen determinante 1, por las propiedades de los determinantes |A*B| = |A| * |B|
por tanto $|L_3*(L_1 * L_2)| = 1$ luego $|C_{12}| = 1$

- g) Demuestre que el producto de matrices triangulares inferiores es una matriz
    triangular inferior.
    ### Respuesta
    Sean $A = (a_{ir}) $ y $B = (a_{sj})$ dos matrices triangulares inferirores, demostremos que $C=AB$ es Triangular inferior
    
    Como son trinagulares inferiores:
    $A_{ij} = 0  y B_{ij} = 0 $ si $ i < j $
    
    Definamos $ C = AB $
    $$ C_{ij} = \sum_{k=1}^{n} A_{ik}B_{kj} $$
    
    Ahora, supongamos que $i < j$, demostremos que $C_{ij} = 0$
    Consideremos un cierto valor de $i \leq k \leq n$ y veamos que el sumando $A_{ik}B_{kj}$ es nulo:
    
    - si $i < j \leq k$ entonces $A_{ik} = 0$ 
    - si $i \leq j < k$ entonces $B_{kj} = 0$
    - si $i < j < k$ entonces $B_{kj} = 0$
    
    Luego, para cualquier valor de k, si $i < j$, $C_{ij} = 0$

- h) Demuestre que la matriz $C_{12}$ es triangular inferior.
### Respuesta
    Las matrices $L_1$, $L_2$ y $L_3$ son triangulares inferiores, y $ C_{12} = L_3*(L_1*L_2)$

    $C_1 = L_1 * L_2$ es matriz triangular inferior por la propiedad demostrada en el inciso anterior

    $L_3 * C_1 = C_{12}$ y además es una matriz triangular inferior por la popiedad demostrada en el inciso anterior

- i) Demuestre que la inversa de una matriz triangular inferior es una matriz triangular inferior.
    ### Respuesta 
    Sea A una matriz truangular inferior
    
    Como A es una matriz triangular inferior, $A^{t}$ es una matriz tringular superior
    
    luego, $(A^{t})^{-1} = (A^{-1})^{t}$ luego $ A^{-1}$ es triangular inferior

- j) Demuestre que si una matriz C es triangular inferior y tiene 1 en la diagonal, entonces la la inversa de C también tiene unos en la diagonal.
### Respuesta

Sea C una matriz triangular inferior con 1 en la diagonal 

$ C = \begin{bmatrix}
 1 & \dots & 0 & 0 & 0\\
 c_{21} & 1 & \dots & 0 \\
 \dots&\dots&1& \dots& 0 \\
 \dots&\dots&\dots&\dots& 0 \\
 c_{n1} &\dots&\dots&a_{n,n-1} & 1 \\
 \end{bmatrix} $
 Utilizando el método de Gauus para hallar la inversa , se tiene que $ \\ $
 $ C^{-1}  = \begin{bmatrix}
 1 & 0 \dots & 0 & 0 & 0\\
 -c_{21} & - c_{22} & \dots & 0 \\
 -c_{31}&-c_{32}&1& \dots& 0 \\
 \dots&\dots&\dots&\dots& 0 \\
 -c_{n1} &\dots&\dots&-c_{n,n-1}&1 \\
 \end{bmatrix} $
 Luego la inversa de C es una matriz diagonal inferior con 1 en la diagonal

- k)Dada una matriz C, triangular inferior con 1 en la diagonal, determine la forma de los elementos de $ C^{-1} $ , donde $ C^{-1} $ es la inversa de C.
### Respuesta
Si C es una matriz diagonal inferior con 1 en la diagonal , los elementos de $ C^{-1} $ tienen la forma si  i = j $ c'[i,j] $ = 1  y si i != j $ c'[i,j] = c[i,j] $  donde c' son los elemtos de $ C^{-1} $ y c los de 

 - l)  Tomando en cuenta que
C12 ∗ A = U32,
que C12 es una matriz triangular inferior, inversible, que U32 es una matriz triangular superior, demuestre que una matriz A de tamaño 3, a la que se le puede aplicar el método de Gauss sin realizar intercambio de filas, se puede expresar com el producto de una matriz triangular inferior con 1 en la diagonal, y una matriz triangular superior, que es la misma matriz que resulta de aplicar el método de Gauss a la matriz A.
### Respuesta
 $ C_{12} \ast A = U_{32} $ multiplicando por $ C^{-1}_{12} $ por la izquierda $ \\ $
      $ C^{-1}_{12}C_{12} A = C^{-1}_{12}U_{32} \\ $
      $ I_nA =  C^{-1}_{12}U_{32} \\ $ 
      $ A =  C^{-1}_{12}U_{32} \\ $
      Luego como $ C_{12} $ es una matriz triangular inferior con 1 en la dioganal $ C^{-1}_{12} $ tambien lo es demostrado anteriormente ; Luego A se puede exprexar como la multiplicación de una matriz trinagular inferior con 1 en la diagonal y una matriz triangular superior con uno en la diagonal 

- m) A partir de los elementos de la matriz A y el método de Gauss ¿qué forma tiene el elementos (i, j), con i > j en la matriz triangular inferior?
### Respuesta
Los elementos (i,j) con i > j tienen la forma $ -a[i,j] $ en la matriz triangular inferior 

# Ejercicio 3: Unicidad de L y U
El objetivo de este ejercicio es demostrar que la descomposición LU de una matriz A cuadrada, a la que se le puede aplicar el método de Gauss sin realizar intercambios de filas, es única.Eso quiere decir que si A = LU, entonces no existen otras dos matrices $ L_1 y
U_1 $ distintas de L y U, respectivamente, tales que $ A = L_1U_1 $.La idea de la demostración es similar a la de muchas demostraciones de unicidad. Lo que hay que hacer es suponer que existen dos descomposiciones $ \\ $
$ L_1U_1 = A = L_2U_2. \\ $ 
Eso significar´ıa que $ \\ $
$ L_1U_1 = L_2U_2. \\ $
Pero, como $ L_i $ y$ U_i $ son inversibles, entonces:
$ L^{-1}_2L_1 = U_2U^{-1}_1 \\ $
y por lo tanto:
$ L_1 = L_2, y U_1 = U_2 \\ $.
Esa es la idea de la demostración. Tu misión en este ejercicio, es rellenar los pasos omitidos de la demostración tomando en cuenta las siguientes pistas:
- La inversa de una triangular inferior es una triangular inferior.
- El producto de dos triangulares inferiores es triangular inferior.
- La inversa de una triangular superior es una triangular superior.
- El producto de dos triangulares superiores es triangular superior.
- ¿Cómo es posible que una triangular inferior sea igual a una triangular superior? :-o.
- La diagonal de $ L_1 y L_2 $ son 1.
- La inversa de una matriz es única. $ \\ $
Y hasta aquí ya puedes enunciar ¡y demostrar! el teorema de la descomposición LU de una matriz, que plantea lo siguiente: $ \\ $
Para toda matriz A, cuadrada, no singular y a la que se le puede aplicar el método de Gauss sin realizar intercambios de filas existen dos matrices únicas L y U tales que A = LU.
# Respuesta 
Dada la matriz A supongamos que $ A = L_1U_1 $ y $ A = L_2U_2 $ tal que $ L_1 != L_2 $ y $ U_1 != U_2 \\ $
$ L_1U_1 = L_2U_2 $  Como L_2 y U_1 son inversibles $ \\ $
$ L^{-1}_{2}L_1 = U_2U^{-1}_1 $ Entonces $ L^{-1}_{2}L_1 $ es una matriz trinagular inferior porque el producto de matrices triangulares inferiores es una matriz trinagular inferior y  $ U_2U^{-1}_1 $ es trinagular inferior porque el producto de matrices trinagulares inferiores es una matriz trinagular inferior $ \\ $
Luego a única matriz que cumple estas condiciones es la matriz identidad $ \\ $
Por tanto : $ \\ $
$ L^{-1}_2L_1 = I_n $ y $ U_2U^{-1}_1 = I_n $
$ L_2 L^{-1}_2L_1 = L_2I_n $ y $ U_2U^{-1}_1U_1 = I_nU_1 $
$ L_1 = L_2 $ y $ U_2 = U_1 $ 
###### Contradición 
Lo supuesto es falso ; por tanto $ A = L_1U_1 $ y $ A = L_2U_2 $ si $ L_1 = L_2 $ y $ U_2 = U_1 $ 

# Ejercicio 4: todo muy lindo, pero ¿qué hacemos con los cambios de fila?
¿Qué hacer en caso de que sean necesarios los cambios de fila? La respuesta es sencilla: ya conoces las matrices de permutaciones que te permiten intercambiar las filas de una matriz. $ \\ $
La solución es: si es necesario hacer intercambios de fila, se multiplica por la matriz P correspondiente para que eso no sea necesario.$ \\ $
¿De dónde sale esa P? ¡De tu implementación eficiente del método de Gauss! Con eso, y puedes explicar por qué la descomposición se llama descomposición PLU.
# Respuesta 
Se llama descomposición PLU porque para la misma se necesitan tres matrices : una matriz P que es una matriz de permutaciones de la matriz identidad que nos permite hacer intercambio de la filas y columnas , una matriz L que es triangular inferior con 1 en la diagonal y una matriz P es que es una matriz triangular superior 