# Tarea 1: Gotta identify them all
- Matriz Diagonal
- Matriz Triangular Superior
- Matriz Triangular Inferior

# Tarea 2: Donde resuelve una eficiente, resuelven 2, 3, ¡y hasta k (con k menor que n)!


# Tarea 3: Método de Gauss + Profes de EDA = Implementación eficiente
Para evitar el intercambio físico de las filas de la matriz, se puede detinar un array de tamaño n, que va a contener los índies de las filas
de la matriz, en un inicio cada indice se encontraría en su posición inicial, y a medida que vaya siendo necesario hacer el cambio de filas,
solamente es necesario cambiar los índices de las filas señaladas. Para acceder a la fila deseada de la matriz, basta con indexar en el valor
que se encuentre en la posicion de la fila deseada en el array de índices

# Tarea 4: ¡3, 1, y 2! Qué permutación más chévere. . .
- a) Al realizar las permutaciones en la matriz ideintidad, y multiplicar ésta por otra matriz (A), se van a efectuar las mismas permutaciones en la matriz A, esto es, si se permutan las columnas 1 y 2 de la matriz ideintidad, el mismo cambio ocurrirá en la matriz resultante, o sea, el elemento en la posición i de la fila j en la matriz A se encontrará en la posición i' (donde i' es la pos en la q se encuentra el 1 en la fila i de P) de la matriz resultante de la multiplicación de P por A
- b) En cada una de las posiciones de la fila, cada elemento [i,j] de la matriz a va a ser multiplicado por el elemento [j,i] de la matriz P, 
     recorriendo la j desde 0-n para cada i, pero de cada una de estas multiplicaciones en cada fila va a haber solo un elemento en el que 
     no se anula, en este caso, para cada ieste va a ser la posición j en la que se encuentra el 1, por tanto, se va a realizar 
     la permutación al multiplicarse A por P
- c) Mediante una permutación de n, en el q el valor de cada posición es la columna que se ha permutado y se encuentra ahora allí
- d) En este caso en vez de permutar las columnas de A, se permutan las filas de A
- e) En este caso, se permutan las columnas
- f) En la matriz ideintidad, permutar las filas o las columanas tiene el mismo efecto, permutar la fila i, con la fila j es equivalente a permutar la columna i con la columna j
- g) Matriz de permutación, matriz de Trabajo?

In [15]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
P = np.array([[0,0,1],[0,1,0],[1,0,0]]) 
P2 = np.array([[0,0,1],[0,1,0],[1,0,0]]) 
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
U = np.array([[1,2,3],[0,5,6],[0,0,9]]) 
L = np.array([[1,0,0],[4,1,0],[7,8,1]])
L@U

array([[ 1,  2,  3],
       [ 4, 13, 18],
       [ 7, 54, 78]])

In [30]:
U

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])